// app/terms/page.tsx
export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="text-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="prose lg:prose-xl">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using AI-Wonderland, you accept and agree to be bound by the terms and provision of this agreement.</p>
        
        <h2>2. Use License</h2>
        <p>Permission is granted to temporarily download one copy of the materials on AI-Wonderland's website for personal, non-commercial transitory viewing only.</p>
        
        <h2>3. User Responsibilities</h2>
        <ul>
          <li>You must not use AI-Wonderland for any illegal purpose</li>
          <li>You are responsible for maintaining the confidentiality of your account</li>
          <li>You agree to notify us immediately of any unauthorized use of your account</li>
        </ul>

        <h2>4. AI-Generated Content</h2>
        <p>Content generated by AI models is provided as-is. Users are responsible for reviewing and validating all AI-generated output.</p>
        
        <h2>5. Limitations of Liability</h2>
        <p>AI-Wonderland shall not be liable for any damages arising out of the use or inability to use the materials on AI-Wonderland's website.</p>
      </div>
    </div>
  );
}
